### PR TITLE
add goober alternative

### PR DESCRIPTION
**Pull request by JoviDeCroock**
I'd also like to suggest these, what do you think:

Forms: [fielder](https://github.com/andyrichardson/fielder) a new approach or [hooked-form](https://github.com/JoviDeCroock/hooked-form) resembles formik. Both are 2kb
Gql client: [urql](https://github.com/FormidableLabs/urql) alternative to apollo for 8kb (no normalised cache and 14kb with)

### CODE REVIEW

**Comment by iamakulov** [comment]
Hey, that’s a great tip, thank you!

* Would you mind formatting the tip per [contribution guidelines](https://github.com/GoogleChromeLabs/webpack-libs-optimizations/blob/master/CONTRIBUTING.md)? Basically, you just need to add a one-line header like `> ⚠ Use with caution / How to enable is ↓ / Added by [AUTHOR](AUTHOR LINK)`
   * I’d also suggest to tune the tip title to something that starts with a verb, like other titles. E.g. “Consider switching to `goober`”
* Could you sign the CLA please? We can’t merge the change without that.

**Comment by JoviDeCroock** [comment]
@iamakulov the cla is signed, the bot doesn't seem to report it though :/

**Comment by iamakulov** [comment]
@JoviDeCroock To confirm:

* Have you signed the CLA with the `de***@gmail.com` email that’s associated with the commit, or with a different email?
* Could you try writing `@googlebot I signed it!`, as googlebot requests? Not sure if Googlebot rechecks are triggered for all comments or for this specific one only.

**Comment by iamakulov** [comment]
Ah cool, it’s good now!

The only thing left: would you mind [formatting the tip](https://github.com/GoogleChromeLabs/webpack-libs-optimizations/pull/24#issuecomment-593129674), please? Thank you!

**Comment by JoviDeCroock** [comment]
There you go @iamakulov 

Would you be interested in hooked-form instead of formik and urql instead of apollo?

**Pull request closed without merging**
